# Generated by Django 4.2.8 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Joseph Flowershop', max_length=255)),
                ('shop_phone', models.CharField(blank=True, max_length=20)),
                ('shop_email', models.EmailField(blank=True, max_length=254)),
                ('shop_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Configuration',
                'verbose_name_plural': 'General Configuration',
                'db_table': 'general_config',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(choices=[('STRIPE', 'Stripe Payment'), ('PAYPAL', 'PayPal'), ('SMS_GATEWAY', 'SMS Gateway'), ('EMAIL', 'Email Service'), ('SHIPPING', 'Shipping Service')], max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='DEVELOPMENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Configuration',
                'verbose_name_plural': 'Service Configurations',
                'db_table': 'service_config',
            },
        ),
    ]
