# Generated by Django 4.2.8 on 2026-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('GCASH', 'GCash'), ('QRPH', 'QRPh'), ('PAYMAYA', 'PayMaya'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
    ]
