# Generated by Django 4.2.8 on 2026-03-16 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('personal_message', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_bouquets/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Bouquet',
                'verbose_name_plural': 'Custom Bouquets',
                'db_table': 'bouquet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BouquetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('flower_count_min', models.PositiveIntegerField(help_text='Minimum flowers for this size')),
                ('flower_count_max', models.PositiveIntegerField(help_text='Maximum flowers for this size')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bouquet Size',
                'verbose_name_plural': 'Bouquet Sizes',
                'db_table': 'bouquet_size',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHOCOLATE', 'Chocolate Box'), ('TEDDY', 'Teddy Bear'), ('BALLOON', 'Balloon'), ('CARD', 'Greeting Card'), ('CANDLE', 'Scented Candle'), ('WINE', 'Wine Bottle')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='extras/')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'extra',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RibbonColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Ribbon Color',
                'verbose_name_plural': 'Ribbon Colors',
                'db_table': 'ribbon_color',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WrappingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('KRAFT', 'Kraft Paper'), ('CELLOPHANE', 'Cellophane'), ('FABRIC', 'Fabric Wrap'), ('BURLAP', 'Burlap'), ('SATIN', 'Satin')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='wrapping_styles/')),
            ],
            options={
                'verbose_name': 'Wrapping Style',
                'verbose_name_plural': 'Wrapping Styles',
                'db_table': 'wrapping_style',
                'ordering': ['style'],
            },
        ),
        migrations.CreateModel(
            name='BouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='custom_bouquet.bouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.flower')),
            ],
            options={
                'verbose_name': 'Bouquet Item',
                'verbose_name_plural': 'Bouquet Items',
                'db_table': 'bouquet_item',
            },
        ),
        migrations.CreateModel(
            name='BouquetExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='custom_bouquet.bouquet')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_bouquet.extra')),
            ],
            options={
                'verbose_name': 'Bouquet Extra',
                'verbose_name_plural': 'Bouquet Extras',
                'db_table': 'bouquet_extra',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='ribbon_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_bouquet.ribboncolor'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_bouquet.bouquetsize'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='wrapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_bouquet.wrappingstyle'),
        ),
    ]
