# Generated by Django 4.2.8 on 2026-03-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('delivery_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_date', models.DateField()),
                ('assigned_to', models.CharField(blank=True, help_text='Assigned delivery personnel', max_length=255)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('delivery_notes', models.TextField(blank=True)),
                ('proof_of_delivery', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'delivery',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.CharField(choices=[('MORNING', 'Morning (8am - 1pm)'), ('AFTERNOON', 'Afternoon (1pm - 8pm)')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_orders', models.PositiveIntegerField(default=20, help_text='Maximum orders for this time window per day')),
            ],
            options={
                'verbose_name': 'Delivery Time Window',
                'verbose_name_plural': 'Delivery Time Windows',
                'db_table': 'delivery_time_window',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
                'db_table': 'delivery_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_time_window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverytimewindow'),
        ),
    ]
