# Generated by Django 4.2.8 on 2026-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
